export const ACTIONS = {
    SET_PROFILE: 'SET_PROFILE',
    LOAD_CONFIGURATIONS: 'LOAD_CONFIGURATIONS',
    CONFIG_USER_DELETE: 'CONFIG_USER_DELETE',
    CONFIG_GROUP_DELETE: 'CONFIG_GROUP_DELETE',
    CONFIG_GROUP_UPDATE: 'CONFIG_GROUP_UPDATE',
    SAVE_ACTIVE_MEETINGS: 'SAVE_ACTIVE_MEETINGS',
    SAVE_HISTORIC_MEETINGS: 'SAVE_HISTORIC_MEETINGS',
    UPDATE_ACTIVE_MEETING: 'UPDATE_ACTIVE_MEETING',
    UPDATE_HISTORIC_MEETING: 'UPDATE_HISTORIC_MEETING',
    UPDATE_USERNAME: 'UPDATE_USERNAME',
};
