export const ACTIONS = {
    SET_PROFILE: 'SET_PROFILE',
    LOAD_CONFIGURATIONS: 'LOAD_CONFIGURATIONS',
    CONFIG_USER_DELETE: 'CONFIG_USER_DELETE',
    CONFIG_GROUP_DELETE: 'CONFIG_GROUP_DELETE',
};
